import { useState } from "react";
import { Download, ChevronDown, FileText, Globe, FileDown, File } from "lucide-react";
import { clsx } from "clsx";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";

interface ExportMenuProps {
  title: string;
  markdown: string;
  html?: string;
}

function wrapHtml(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 720px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 2em; border-bottom: 1px solid #eee; padding-bottom: 0.3em; }
    h2 { font-size: 1.5em; margin-top: 1.5em; }
    h3 { font-size: 1.2em; margin-top: 1.2em; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
    pre { background: #f4f4f4; padding: 16px; border-radius: 6px; overflow-x: auto; }
    pre code { background: none; padding: 0; }
    blockquote { border-left: 3px solid #ddd; margin-left: 0; padding-left: 16px; color: #555; }
    ul, ol { padding-left: 1.5em; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #f8f8f8; }
    hr { border: none; border-top: 1px solid #eee; margin: 2em 0; }
    img { max-width: 100%; }
  </style>
</head>
<body>
${bodyHtml}
<footer style="margin-top: 3em; padding-top: 1em; border-top: 1px solid #eee; font-size: 0.85em; color: #999;">
  Generated by Compass
</footer>
</body>
</html>`;
}

function markdownToHtml(markdown: string): string {
  // Basic markdown to HTML conversion
  let html = markdown;

  // Headings
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");

  // Bold and italic
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.+?)\*/g, "<em>$1</em>");
  html = html.replace(/~~(.+?)~~/g, "<del>$1</del>");
  html = html.replace(/`([^`]+)`/g, "<code>$1</code>");

  // Horizontal rule
  html = html.replace(/^---$/gm, "<hr>");

  // Lists
  html = html.replace(/^- \[x\] (.+)$/gm, '<li style="list-style: none;"><input type="checkbox" checked disabled> $1</li>');
  html = html.replace(/^- \[ \] (.+)$/gm, '<li style="list-style: none;"><input type="checkbox" disabled> $1</li>');
  html = html.replace(/^- (.+)$/gm, "<li>$1</li>");
  html = html.replace(/^(\d+)\. (.+)$/gm, "<li>$2</li>");

  // Blockquote
  html = html.replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>");

  // Paragraphs — wrap orphan lines
  html = html.replace(/^(?!<[a-z])((?!$).+)$/gm, "<p>$1</p>");

  // Clean up empty paragraphs
  html = html.replace(/<p><\/p>/g, "");

  return html;
}

function markdownToDocx(title: string, markdown: string): Document {
  const paragraphs: Paragraph[] = [];
  const lines = markdown.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (trimmed.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: trimmed.slice(4) })],
        }),
      );
    } else if (trimmed.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: trimmed.slice(3) })],
        }),
      );
    } else if (trimmed.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: trimmed.slice(2) })],
        }),
      );
    } else if (trimmed.startsWith("- ")) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: parseInlineRuns(trimmed.slice(2)),
        }),
      );
    } else if (/^\d+\. /.test(trimmed)) {
      paragraphs.push(
        new Paragraph({
          numbering: { reference: "default-numbering", level: 0 },
          children: parseInlineRuns(trimmed.replace(/^\d+\. /, "")),
        }),
      );
    } else if (trimmed === "---") {
      paragraphs.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "———" })],
        }),
      );
    } else if (trimmed.startsWith("> ")) {
      paragraphs.push(
        new Paragraph({
          indent: { left: 720 },
          children: [new TextRun({ text: trimmed.slice(2), italics: true })],
        }),
      );
    } else {
      paragraphs.push(
        new Paragraph({ children: parseInlineRuns(trimmed) }),
      );
    }
  }

  return new Document({
    sections: [{ children: paragraphs }],
    numbering: {
      config: [
        {
          reference: "default-numbering",
          levels: [
            {
              level: 0,
              format: "decimal" as never,
              text: "%1.",
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
  });
}

function parseInlineRuns(text: string): TextRun[] {
  const runs: TextRun[] = [];
  // Simple inline parsing: **bold**, *italic*, `code`
  const regex = /\*\*(.+?)\*\*|\*(.+?)\*|`(.+?)`|([^*`]+)/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    if (match[1]) {
      runs.push(new TextRun({ text: match[1], bold: true }));
    } else if (match[2]) {
      runs.push(new TextRun({ text: match[2], italics: true }));
    } else if (match[3]) {
      runs.push(new TextRun({ text: match[3], font: "Courier New", size: 20 }));
    } else if (match[4]) {
      runs.push(new TextRun({ text: match[4] }));
    }
  }
  return runs.length > 0 ? runs : [new TextRun({ text })];
}

export default function ExportMenu({ title, markdown, html }: ExportMenuProps) {
  const [showMenu, setShowMenu] = useState(false);
  const [exporting, setExporting] = useState(false);

  const slug = title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

  async function exportAs(format: "md" | "html" | "pdf" | "docx") {
    setExporting(true);
    setShowMenu(false);

    try {
      if (format === "docx") {
        const doc = markdownToDocx(title, markdown);
        const blob = await Packer.toBlob(doc);
        const buffer = await blob.arrayBuffer();
        const bytes = new Uint8Array(buffer);
        let binary = "";
        for (let i = 0; i < bytes.length; i++) {
          binary += String.fromCharCode(bytes[i]);
        }
        const base64 = btoa(binary);
        await window.compass?.app.exportDocument(
          `${slug}.docx`,
          base64,
          "docx",
        );
        return;
      }

      const fileName = `${slug}.${format}`;

      if (format === "md") {
        await window.compass?.app.exportDocument(fileName, markdown, "md");
      } else {
        const bodyHtml = html || markdownToHtml(markdown);
        const fullHtml = wrapHtml(title, bodyHtml);
        await window.compass?.app.exportDocument(fileName, fullHtml, format);
      }
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        disabled={exporting}
        className={clsx(
          "flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg transition-colors",
          "text-compass-muted hover:text-compass-text hover:bg-white/5",
        )}
      >
        <Download className="w-4 h-4" />
        Export
        <ChevronDown className="w-3 h-3" />
      </button>

      {showMenu && !exporting && (
        <div className="absolute top-full right-0 mt-1 w-48 bg-compass-card border border-compass-border rounded-lg shadow-xl z-50 overflow-hidden">
          <div className="py-1">
            <button
              onClick={() => exportAs("md")}
              className="w-full flex items-center gap-2 px-3 py-2 text-sm text-compass-muted hover:text-compass-text hover:bg-white/5 transition-colors"
            >
              <FileText className="w-4 h-4" />
              Markdown (.md)
            </button>
            <button
              onClick={() => exportAs("html")}
              className="w-full flex items-center gap-2 px-3 py-2 text-sm text-compass-muted hover:text-compass-text hover:bg-white/5 transition-colors"
            >
              <Globe className="w-4 h-4" />
              HTML (.html)
            </button>
            <button
              onClick={() => exportAs("pdf")}
              className="w-full flex items-center gap-2 px-3 py-2 text-sm text-compass-muted hover:text-compass-text hover:bg-white/5 transition-colors"
            >
              <FileDown className="w-4 h-4" />
              PDF (.pdf)
            </button>
            <button
              onClick={() => exportAs("docx")}
              className="w-full flex items-center gap-2 px-3 py-2 text-sm text-compass-muted hover:text-compass-text hover:bg-white/5 transition-colors"
            >
              <File className="w-4 h-4" />
              Word (.docx)
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
