"""Data analysis models — structured output from the Analyst engine."""

from __future__ import annotations

from pydantic import BaseModel, Field


class SuggestedQuery(BaseModel):
    """A suggested investigative query for deeper analysis."""

    description: str = ""
    query: str = ""
    data_source: str = ""


class DataAnalysis(BaseModel):
    """A structured data analysis for a product question."""

    key_finding: str = ""
    interpretation: str = ""
    data_gaps: list[str] = Field(default_factory=list)
    suggested_queries: list[SuggestedQuery] = Field(default_factory=list)
    product_implications: str = ""
    evidence_citations: list[str] = Field(default_factory=list)

    def to_markdown(self) -> str:
        lines = ["# Data Analysis", ""]

        if self.key_finding:
            lines.extend(["## Key Finding", "", self.key_finding, ""])

        if self.interpretation:
            lines.extend(["## Interpretation", "", self.interpretation, ""])

        if self.data_gaps:
            lines.extend(["## Data Gaps", ""])
            for g in self.data_gaps:
                lines.append(f"- {g}")
            lines.append("")

        if self.suggested_queries:
            lines.extend(["## Suggested Queries", ""])
            for sq in self.suggested_queries:
                lines.append(f"### {sq.description}")
                if sq.data_source:
                    lines.append(f"*Source: {sq.data_source}*")
                if sq.query:
                    lines.append(f"\n```sql\n{sq.query}\n```")
                lines.append("")

        if self.product_implications:
            lines.extend(["## Product Implications", "", self.product_implications, ""])

        if self.evidence_citations:
            lines.extend(["## Evidence", ""])
            for c in self.evidence_citations:
                lines.append(f"- {c}")
            lines.append("")

        lines.extend(["---", "*Generated by Compass Analyst*"])
        return "\n".join(lines)
