"""Challenge models — structured output from the Challenger engine."""

from __future__ import annotations

from pydantic import BaseModel, Field


class Challenge(BaseModel):
    """A structured devil's advocate challenge of a product opportunity."""

    title: str
    weaknesses: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    contradicting_evidence: list[str] = Field(default_factory=list)
    evidence_quality_score: float = 0.0
    overall_assessment: str = ""

    def to_markdown(self) -> str:
        lines = [
            f"# Challenge: {self.title}",
            "",
        ]

        if self.overall_assessment:
            lines.extend([
                "## Overall Assessment",
                "",
                self.overall_assessment,
                "",
            ])

        lines.append(f"**Evidence Quality Score:** {self.evidence_quality_score:.1f}/10")
        lines.append("")

        if self.weaknesses:
            lines.extend(["## Weaknesses", ""])
            for w in self.weaknesses:
                lines.append(f"- {w}")
            lines.append("")

        if self.missing_evidence:
            lines.extend(["## Missing Evidence", ""])
            for m in self.missing_evidence:
                lines.append(f"- {m}")
            lines.append("")

        if self.assumptions:
            lines.extend(["## Unverified Assumptions", ""])
            for a in self.assumptions:
                lines.append(f"- {a}")
            lines.append("")

        if self.risks:
            lines.extend(["## Risks", ""])
            for r in self.risks:
                lines.append(f"- {r}")
            lines.append("")

        if self.contradicting_evidence:
            lines.extend(["## Contradicting Evidence", ""])
            for c in self.contradicting_evidence:
                lines.append(f"- {c}")
            lines.append("")

        lines.extend(["---", "*Generated by Compass Challenger*"])

        return "\n".join(lines)
