"""Document models — structured output from the Writer engine."""

from __future__ import annotations

from pydantic import BaseModel, Field


class Requirement(BaseModel):
    """A product requirement with priority level."""

    description: str
    priority: str = "P1"  # P0, P1, P2


class ProductBrief(BaseModel):
    """An evidence-grounded product brief / PRD."""

    title: str
    problem_statement: str
    target_audience: str = ""
    proposed_solution: str = ""
    requirements: list[Requirement] = Field(default_factory=list)
    success_metrics: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    evidence_citations: list[str] = Field(default_factory=list)

    def to_markdown(self) -> str:
        lines = [
            f"# Product Brief: {self.title}",
            "",
            "## Problem Statement",
            "",
            self.problem_statement,
            "",
        ]

        if self.target_audience:
            lines.extend(["## Target Audience", "", self.target_audience, ""])

        if self.proposed_solution:
            lines.extend(["## Proposed Solution", "", self.proposed_solution, ""])

        if self.requirements:
            lines.extend(["## Requirements", ""])
            for req in self.requirements:
                lines.append(f"- **[{req.priority}]** {req.description}")
            lines.append("")

        if self.success_metrics:
            lines.extend(["## Success Metrics", ""])
            for metric in self.success_metrics:
                lines.append(f"- {metric}")
            lines.append("")

        if self.risks:
            lines.extend(["## Risks", ""])
            for risk in self.risks:
                lines.append(f"- {risk}")
            lines.append("")

        if self.evidence_citations:
            lines.extend(["## Evidence", ""])
            for cite in self.evidence_citations:
                lines.append(f"- {cite}")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Compass*")

        return "\n".join(lines)


class SourceChanges(BaseModel):
    """Changes detected in a single source type."""

    source_type: str
    summary: str
    items: list[str] = Field(default_factory=list)


class StakeholderUpdate(BaseModel):
    """An evidence-grounded stakeholder update / status report."""

    title: str
    period: str = ""
    summary: str = ""
    changes_by_source: list[SourceChanges] = Field(default_factory=list)
    new_signals: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    next_steps: list[str] = Field(default_factory=list)
    evidence_freshness: str = ""

    def to_markdown(self) -> str:
        lines = [
            f"# Stakeholder Update: {self.title}",
        ]

        if self.period:
            lines.append(f"*Period: {self.period}*")
        lines.append("")

        if self.summary:
            lines.extend(["## Summary", "", self.summary, ""])

        if self.changes_by_source:
            lines.extend(["## Changes by Source", ""])
            for change in self.changes_by_source:
                lines.append(f"### {change.source_type}")
                lines.append(change.summary)
                for item in change.items:
                    lines.append(f"- {item}")
                lines.append("")

        if self.new_signals:
            lines.extend(["## New Signals", ""])
            for signal in self.new_signals:
                lines.append(f"- {signal}")
            lines.append("")

        if self.risks:
            lines.extend(["## Risks & Concerns", ""])
            for risk in self.risks:
                lines.append(f"- {risk}")
            lines.append("")

        if self.next_steps:
            lines.extend(["## Next Steps", ""])
            for step in self.next_steps:
                lines.append(f"- {step}")
            lines.append("")

        if self.evidence_freshness:
            lines.extend(["---", f"*Evidence freshness: {self.evidence_freshness}*"])

        lines.extend(["", "---", "*Generated by Compass*"])

        return "\n".join(lines)
