"""Planning models — structured output from the Planner engine."""

from __future__ import annotations

from pydantic import BaseModel, Field


class FocusArea(BaseModel):
    """A recommended area of focus for the coming week."""

    title: str
    reason: str = ""
    priority: str = "medium"  # high, medium, low
    related_opportunities: list[str] = Field(default_factory=list)


class ConfidenceChange(BaseModel):
    """A change in confidence for an opportunity between discovery runs."""

    opportunity: str
    direction: str = ""  # up, down, stable
    reason: str = ""


class WeeklyPlan(BaseModel):
    """A structured weekly plan synthesized from all product evidence."""

    summary: str = ""
    focus_areas: list[FocusArea] = Field(default_factory=list)
    stale_sources: list[str] = Field(default_factory=list)
    new_signals: list[str] = Field(default_factory=list)
    confidence_changes: list[ConfidenceChange] = Field(default_factory=list)
    suggested_actions: list[str] = Field(default_factory=list)
    evidence_freshness: str = ""

    def to_markdown(self) -> str:
        lines = ["# Weekly Plan", ""]

        if self.summary:
            lines.extend([self.summary, ""])

        if self.focus_areas:
            lines.extend(["## Focus Areas", ""])
            for fa in self.focus_areas:
                priority_badge = {"high": "!!!", "medium": "!!", "low": "!"}.get(fa.priority, "!!")
                lines.append(f"### [{priority_badge}] {fa.title}")
                if fa.reason:
                    lines.append(f"{fa.reason}")
                if fa.related_opportunities:
                    lines.append(f"*Related:* {', '.join(fa.related_opportunities)}")
                lines.append("")

        if self.new_signals:
            lines.extend(["## New Signals", ""])
            for s in self.new_signals:
                lines.append(f"- {s}")
            lines.append("")

        if self.confidence_changes:
            lines.extend(["## Confidence Changes", ""])
            for cc in self.confidence_changes:
                arrow = {"up": "+", "down": "-", "stable": "="}.get(cc.direction, "?")
                lines.append(f"- [{arrow}] **{cc.opportunity}**: {cc.reason}")
            lines.append("")

        if self.stale_sources:
            lines.extend(["## Stale Sources", ""])
            for s in self.stale_sources:
                lines.append(f"- {s}")
            lines.append("")

        if self.suggested_actions:
            lines.extend(["## Suggested Actions", ""])
            for i, a in enumerate(self.suggested_actions, 1):
                lines.append(f"{i}. {a}")
            lines.append("")

        if self.evidence_freshness:
            lines.extend(["## Evidence Freshness", "", self.evidence_freshness, ""])

        lines.extend(["---", "*Generated by Compass Planner*"])
        return "\n".join(lines)
